name: uas_pemrogramanmobile
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/data.json

dart_obfuscation: true
